#Import Library

In [ ]:
import numpy as np # Untuk Komputasi Numerik
import pandas as pd # Untuk Manipulasi Data
import matplotlib.pyplot as plt # Untuk Memvisualisasikan Data
import seaborn as sns # Untuk Memvisualisasikan Data
import warnings
import string
import re
warnings.filterwarnings("ignore") # Untuk Mengabaikan Warnings

#Mount Drive

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

#Read Data

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/Dataku/Dataset/dataset Bansos COVID19.csv") #dataframe
df.head()

   index                                              tweet sentiment
0      0                  bangsat koruptor bansos adem ayem  Negative
1      1  biasalah namanya cari kesalahan nya cari cari ...  Negative
2      2  emang sampeyan balikin bang beneran nih nanya ...  Negative
3      3  wooooiiiiiiurus tuh harun masiku ektp century ...  Negative
4      4  smoga dana bansos ampe serngan fajar pdip smpa...  Negative

In [ ]:
df.shape

(702, 3)

In [ ]:
df.describe()

            index
count  702.000000
mean   350.222222
std    202.446701
min      0.000000
25%    175.250000
50%    350.500000
75%    524.750000
max    700.000000

In [ ]:
#cek tipe data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 702 entries, 0 to 701
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   index      702 non-null    int64
 1   tweet      702 non-null    object
 2   sentiment  702 non-null    object
dtypes: int64(1), object(2)
memory usage: 16.6+ KB

In [ ]:
#cek missing value
df.isnull().sum()

index        0
tweet        0
sentiment    0
dtype: int64

In [ ]:
df.isnull() #dropna, fungsi untuk menghapus missing value

     index  tweet  sentiment
0    False  False      False
1    False  False      False
2    False  False      False
3    False  False      False
4    False  False      False
..     ...    ...        ...
697  False  False      False
698  False  False      False
699  False  False      False
700  False  False      False
701  False  False      False

[702 rows x 3 columns]

In [ ]:
df['sentiment'].value_counts()

Negative    374
Positive    328
Name: sentiment, dtype: int64

In [ ]:
#hapus kolom index
df.drop("index", axis=1, inplace=True)

In [ ]:
df.head()

                                               tweet sentiment
0                  bangsat koruptor bansos adem ayem  Negative
1  biasalah namanya cari kesalahan nya cari cari ...  Negative
2  emang sampeyan balikin bang beneran nih nanya ...  Negative
3  wooooiiiiiiurus tuh harun masiku ektp century ...  Negative
4  smoga dana bansos ampe serngan fajar pdip smpa...  Negative

#Preprocessing

Lowercase

In [ ]:
def lowercase(dataset):
  return dataset.apply(lambda x: ''.join([w for w in x.lower()]))

df['Clean_text'] = lowercase(df['tweet'])
df

,tweet,sentiment,Clean_text
0,bangsat koruptor bansos adem ayem,Negative,bangsat koruptor bansos adem ayem
1,biasalah namanya cari kesalahan nya cari cari ...,Negative,biasalah namanya cari kesalahan nya cari cari ...
2,emang sampeyan balikin bang beneran nih nanya ...,Negative,emang sampeyan balikin bang beneran nih nanya ...
3,wooooiiiiiiurus tuh harun masiku ektp century ...,Negative,wooooiiiiiiurus tuh harun masiku ektp century ...
4,smoga dana bansos ampe serngan fajar pdip smpa...,Negative,smoga dana bansos ampe serngan fajar pdip smpa...
...,...,...,...
697,"Peduli Warga Ditengah Pandemi Covid19, Kapolre...",Positive,"peduli warga ditengah pandemi covid19, kapolre..."
698,Kapolda Jatim Bantu Masyarakat Terdampak Pande...,Positive,kapolda jatim bantu masyarakat terdampak pande...
699,"Kepedulian di Masa Pandemi, Kapolresta Palangk...",Positive,"kepedulian di masa pandemi, kapolresta palangk..."
700,Gw juga berdoa semoga Indonesia dijauhkan dari...,Positive,gw juga berdoa semoga indonesia dijauhkan dari...
701,Selain dukungannya untuk UMKM Indonesia yang l...,Positive,selain dukungannya untuk umkm indonesia yang l...


Data Cleansing
Remove URL, Username, Character, Short Words

In [ ]:
def preprocess_remove(to_remove, Clean_text):
    r = re.findall(to_remove, Clean_text)
    for i in r:
        Clean_text = re.sub(i, '', Clean_text)
    return Clean_text
df['Clean_text'] = np.vectorize(preprocess_remove)('http[\w]*',df['Clean_text'])
df['Clean_text'] = np.vectorize(preprocess_remove)('@[\w]*',df['Clean_text'])
df['Clean_text'] = df['Clean_text'].str.replace('[^a-zA-Z]', ' ')
df['Clean_text'] = df['Clean_text'].apply(lambda x: ' '.join([w for w in x.split() if len(w)>3]))
df

,tweet,sentiment,Clean_text
0,bangsat koruptor bansos adem ayem,Negative,bangsat koruptor bansos adem ayem
1,biasalah namanya cari kesalahan nya cari cari ...,Negative,biasalah namanya cari kesalahan cari cari salah
2,emang sampeyan balikin bang beneran nih nanya ...,Negative,emang sampeyan balikin bang beneran nanya nany...
3,wooooiiiiiiurus tuh harun masiku ektp century ...,Negative,wooooiiiiiiurus harun masiku ektp century koru...
4,smoga dana bansos ampe serngan fajar pdip smpa...,Negative,smoga dana bansos ampe serngan fajar pdip smpa...
...,...,...,...
697,"Peduli Warga Ditengah Pandemi Covid19, Kapolre...",Positive,peduli warga ditengah pandemi covid kapolres c...
698,Kapolda Jatim Bantu Masyarakat Terdampak Pande...,Positive,kapolda jatim bantu masyarakat terdampak pande...
699,"Kepedulian di Masa Pandemi, Kapolresta Palangk...",Positive,kepedulian masa pandemi kapolresta palangka ra...
700,Gw juga berdoa semoga Indonesia dijauhkan dari...,Positive,juga berdoa semoga indonesia dijauhkan dari or...
701,Selain dukungannya untuk UMKM Indonesia yang l...,Positive,selain dukungannya untuk umkm indonesia yang l...

Tokenisasi & Stemming

In [ ]:
pip install sastrawi

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting sastrawi
  Downloading Sastrawi-1.0.1-py2.py3-none-any.whl (209 kB)
     |████████████████████████████████| 209 kB 2.1 MB/s
Installing collected packages: sastrawi
Successfully installed sastrawi-1.0.1

In [ ]:
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
factory = StemmerFactory()
stemmer = factory.create_stemmer()

In [ ]:
def stem_sentences(sentence):
    tokens = sentence.split()
    stemmed_tokens = [stemmer.stem(token) for token in tokens]
    return ' '.join(stemmed_tokens)

In [ ]:
df['Clean_text'] = df['Clean_text'].apply(stem_sentences)

In [ ]:
df

,tweet,sentiment,Clean_text
0,bangsat koruptor bansos adem ayem,Negative,bangsat koruptor bansos adem ayem
1,biasalah namanya cari kesalahan nya cari cari ...,Negative,biasa nama cari salah cari cari salah
2,emang sampeyan balikin bang beneran nih nanya ...,Negative,emang sampeyan balikin bang beneran nanya nany...
3,wooooiiiiiiurus tuh harun masiku ektp century ...,Negative,wooooiiiiiiurus harun mas ektp century korupsi...
4,smoga dana bansos ampe serngan fajar pdip smpa...,Negative,smoga dana bansos ampe serngan fajar pdip smpa...
...,...,...,...
697,"Peduli Warga Ditengah Pandemi Covid19, Kapolre...",Positive,peduli warga tengah pandemi covid kapolres cik...
698,Kapolda Jatim Bantu Masyarakat Terdampak Pande...,Positive,kapolda jatim bantu masyarakat dampak pandemi ...
699,"Kepedulian di Masa Pandemi, Kapolresta Palangk...",Positive,peduli masa pandemi kapolresta palangka raya s...
700,Gw juga berdoa semoga Indonesia dijauhkan dari...,Positive,juga doa moga indonesia jauh dari orang korups...
701,Selain dukungannya untuk UMKM Indonesia yang l...,Positive,selain dukung untuk umkm indonesia yang luar b...

In [ ]:
df.head(30)

,tweet,sentiment,Clean_text
0,bangsat koruptor bansos adem ayem,Negative,bangsat koruptor bansos adem ayem
1,biasalah namanya cari kesalahan nya cari cari ...,Negative,biasa nama cari salah cari cari salah
2,emang sampeyan balikin bang beneran nih nanya ...,Negative,emang sampeyan balikin bang beneran nanya nany...
3,wooooiiiiiiurus tuh harun masiku ektp century ...,Negative,wooooiiiiiiurus harun mas ektp century korupsi...
4,smoga dana bansos ampe serngan fajar pdip smpa...,Negative,smoga dana bansos ampe serngan fajar pdip smpa...
5,bansos bpnt kau sembako juni terdaftar website...,Positive,bansos bpnt sembako juni daftar website bansos...
6,mending lu jagain bansos gak dikorup kawanlu k...,Negative,mending jagain bansos korup kawanlu kebaperan
7,dana bansos aja dikorupsi berlagak jd auditor ...,Negative,dana bansos korupsi lagak auditor diketawain o...
8,tetima kasih ppkm semoga usaha nasi bungkus ba...,Positive,tetima kasih ppkm moga usaha nasi bungkus bangkit
9,bansos diganti pemberdayaan ekonomi juta warga...,Negative,bansos ganti daya ekonomi juta warga miskin
10,trauma,Negative,trauma
11,yg korupsi bansos yg korupsi minyak goreng yg ...,Negative,korupsi bansos korupsi minyak goreng korupsi diem
12,sumber masalah,Negative,sumber masalah
13,harun masiku ktp el bansos dah gimana,Negative,harun mas bansos gimana
14,pdip sumber masalah,Negative,pdip sumber masalah
15,rugi trilyunan rupiah bansos sasaran,Negative,rugi trilyunan rupiah bansos sasar
16,pln rugi peamina rugi bumn rugibansos asabri d...,Negative,rugi peamina rugi bumn rugibansos asabri diam ...
17,orang hebat berkumpul nya dgn pemimpin duniada...,Negative,orang hebat kumpul pimpin duniadan aku duniake...
18,kagak yg ilang uang dki,Negative,kagak ilang uang
19,jakaatemuan badan pemeriksa keuangan bpk terka...,Negative,jakaatemuan badan periksa uang kait dana bantu...
20,kpk ott kepala daerah ya,Negative,kepala daerah
21,bansos tuh urus,Negative,bansos urus
22,kebijakan dilaksanakan daya beli rakyat miskin...,Negative,bijak laksana daya beli rakyat miskin anjlok
23,ati ati kandang waspadalah waspadalah kesengsa...,Negative,kandang waspada waspada sengsara ulang bungkus...
24,cek bansos kemensos juni pemilik ktp penerima ...,Positive,bansos kemensos juni milik terima bpnt ciri kh...
25,korupsi minyak goreng korupsi bansos kasihan r...,Negative,korupsi minyak goreng korupsi bansos kasihan r...
26,heh hamburkan duit lupa hutang ln yg dicetak p...,Negative,hambur duit lupa hutang cetak presiden korupsi...
27,lu jajal nyinyir gibran bansos lu diserbu gak ...,Negative,jajal nyinyir gibran bansos serbu fenboys pres
28,tajir tp gak duit pakai fasilitas negara lbh m...,Negative,tajir duit pakai fasilitas negara miskin terim...
29,dampak dri dungunya penjilat,Negative,dampak dungu jilat

In [ ]:
from nltk.corpus import stopwords
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [ ]:
stop_words = stopwords.words('indonesian')

In [ ]:
import string
new_tweet_text = []
word_dic = []
for text in df['Clean_text']:
    new_text = []
    for word in text.split():
        if word.lower() not in stop_words:
            new_text.append(word.lower())
            word_dic.append(word.lower())
    new_text = " ".join(new_text)
    new_tweet_text.append(new_text)
    
df['Clean_text'] = new_tweet_text

In [ ]:
df

,tweet,sentiment,Clean_text
0,bangsat koruptor bansos adem ayem,Negative,bangsat koruptor bansos adem ayem
1,biasalah namanya cari kesalahan nya cari cari ...,Negative,nama cari salah cari cari salah
2,emang sampeyan balikin bang beneran nih nanya ...,Negative,emang sampeyan balikin bang beneran nanya nany...
3,wooooiiiiiiurus tuh harun masiku ektp century ...,Negative,wooooiiiiiiurus harun mas ektp century korupsi...
4,smoga dana bansos ampe serngan fajar pdip smpa...,Negative,smoga dana bansos ampe serngan fajar pdip smpa...
...,...,...,...
697,"Peduli Warga Ditengah Pandemi Covid19, Kapolre...",Positive,peduli warga pandemi covid kapolres ciko bazna...
698,Kapolda Jatim Bantu Masyarakat Terdampak Pande...,Positive,kapolda jatim bantu masyarakat dampak pandemi ...
699,"Kepedulian di Masa Pandemi, Kapolresta Palangk...",Positive,peduli pandemi kapolresta palangka raya salur ...
700,Gw juga berdoa semoga Indonesia dijauhkan dari...,Positive,doa moga indonesia orang korupsi sumbang banso...
701,Selain dukungannya untuk UMKM Indonesia yang l...,Positive,dukung umkm indonesia salur bansos pandemi

Remove words - Custom (singkatan, alay, dll)

In [ ]:
custom = ['ya','yg','min','banget','bgt','udah', 'pake','pakai','kalo','kali','mulu','gini','kasih','ilang','gimana','pdhl','lot', 'lu', 'tp', 'heh', 'dri', '']

In [ ]:
df['Clean_text'] = df['Clean_text'].apply(lambda x: ' '.join([item for item in x.split() if item not in custom]))

In [ ]:
df
df.to_csv('hasilku.csv')